In [2]:
import torch.nn as nn
import torch

In [30]:
loss

tensor([1.7478, 1.5728, 2.2054], grad_fn=<NllLossBackward0>)

In [53]:
criterion = nn.CrossEntropyLoss(reduction="none")
# b, classes, pixels
output = torch.randint(0,2, (3, 4, 5)).type(torch.float)

# b, pixels with values of classes
target = torch.randint(0,4,size=(3, 5)).type(torch.LongTensor)
loss = criterion(output, target)

In [54]:
output 
# b, classes
# b, pixels (binary classification)


# b, pixels, classes. 


tensor([[[0., 0., 0., 0., 1.],
         [1., 0., 0., 1., 0.],
         [1., 0., 0., 1., 1.],
         [0., 0., 0., 1., 0.]],

        [[1., 1., 0., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 0., 0., 0.],
         [1., 0., 0., 0., 1.]],

        [[0., 0., 0., 1., 1.],
         [1., 1., 1., 1., 1.],
         [0., 1., 0., 1., 0.],
         [1., 0., 1., 1., 1.]]])

In [55]:
target

tensor([[3, 2, 3, 0, 2],
        [2, 3, 2, 3, 0],
        [0, 3, 3, 3, 1]])

In [56]:
loss

tensor([[2.0064, 1.3863, 1.3863, 2.2143, 1.0064],
        [1.3863, 2.2143, 1.7437, 1.3863, 1.2143],
        [2.0064, 2.0064, 1.0064, 1.3863, 1.2143]])

In [23]:
import torch
a = [torch.randn(2, 2), torch.randn(2, 2), torch.randn(2, 2)]
a

[tensor([[-0.5305,  1.2313],
         [ 0.7626,  1.7983]]),
 tensor([[-0.4522, -0.0570],
         [ 1.8869,  1.1403]]),
 tensor([[-0.3279, -0.6617],
         [-0.4655,  0.1577]])]

In [24]:
b = torch.block_diag(*a)
b.shape

torch.Size([6, 6])

In [20]:
b

tensor([[ 1.0875, -0.3608,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.7705, -1.6977,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -1.2726, -1.0366,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.3800, -1.0822,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  1.0107,  1.3600],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -0.1734,  0.6759]])